### ISSUE TITLE
LocusMap don't render in small screen devices

### ISSUE THREAD

**Issue by luispalacios270** [luispalacios270/inappbrowser-locusmaps-integration#2]
## Context
An IONIC application launch a webview with the InAppBrowser module.

## Expected Result
The Map should be loaded and shown in any device.

## Problem
The Map doesn't load in any device screen with a width lower than 581 px.

Using Chrome Toggle device tool and setting the sreen width size to 580px or lower the problem can be reproduce

![screen shot 2018-01-31 at 10 18 44 am](https://user-images.githubusercontent.com/18171821/35630736-29e0ba76-0670-11e8-9223-d9c0deea63c2.png)

If the screen size is 581px or higher the map is loaded.

![screen shot 2018-01-31 at 10 22 23 am](https://user-images.githubusercontent.com/18171821/35631026-d2711424-0670-11e8-960a-c093903ad6a8.png)

The console area shows this error when the map isn't loaded due the screen width size:

```javascript
[ERROR:/index.js] | EXCEPTION "Cannot read property `assetVersion` of undefined"
    @TypeError: Cannot read property 'assetVersion' of undefined
    @at Object.eval (eval at e.exports (https://js.locuslabs.com/latest/locuslabs.js:1:4433319), <anonymous>:2:788912)
    @at r (eval at e.exports (https://js.locuslabs.com/latest/locuslabs.js:1:4433319), <anonymous>:2:1128197)
    @at Generator.eval [as _invoke] (eval at e.exports (https://js.locuslabs.com/latest/locuslabs.js:1:4433319), <anonymous>:2:1129317)
    @at Generator.t.(anonymous function) [as next] (eval at e.exports (https://js.locuslabs.com/latest/locuslabs.js:1:4433319), <anonymous>:2:1128376)
    @at p (eval at e.exports (https://js.locuslabs.com/latest/locuslabs.js:1:4433319), <anonymous>:2:484095)
    @at Object.n [as cont] (eval at e.exports (https://js.locuslabs.com/latest/locuslabs.js:1:4433319), <anonymous>:2:484769)
    @at y (eval at e.exports (https://js.locuslabs.com/latest/locuslabs.js:1:4433319), <anonymous>:2:484585)
    @at Object.t.cont (eval at e.exports (https://js.locuslabs.com/latest/locuslabs.js:1:4433319), <anonymous>:2:483057)
    @at p (eval at e.exports (https://js.locuslabs.com/latest/locuslabs.js:1:4433319), <anonymous>:2:484143)
    @at Object.n [as cont] (eval at e.exports (https://js.locuslabs.com/latest/locuslabs.js:1:4433319), <anonymous>:2:484769) 
```

### Reproducing the error: 
1. In *Google Chrome* (Or any navigator whatsoever) go to [LocusMap Page](http://locusmap-test.singlehtml.com) This page is a simple html with *Locusmap*.
2. Resize the window with Device Toggle Tool in Google Chrome or just resizing the entire app window to math any width lower than 581 px.
3. Refresh the page in order to reload the Map with the conditions mentioned before.

## Additional Information

1. Once the map is loaded with 581px width screen the width can be resize without problems.
2. Since mostly devices have an inferior width in portrait mode the map can only be loaded in landscape mode only if in this mode the screen width if higher than 580 px.
3. As mentioned before, *once the map is loaded* in devices in landscape mode the map works fine in portrait mode.
4. The problem was reproduced in both Google Chrome and Safari.

**Comment by manuel-gutierrezp** [comment]
Hi there. 

It was an authentication problem.  The account Id used did not have access to the lhr mobile API. Now the issue should be resolved.

Thanks for the detailed bug description.

**Comment by luispalacios270** [comment]
@manuel-gutierrezp I'm glad the problem is solved. i'm closing the issue then.
